### ISSUE TITLE
s.replace is not a function

### ISSUE THREAD

**Issue by u12206050** [juliangruber/capture-electron#1]
It seems it is trying to run "shellescape" function on an object.

This is the array that is sent to shellescape:

```
0: { // THIS OBJECT BREAKS IT
 // It seems to be an electron instance.
}
1:"/Users/…/…/…/node_modules/capture-electron/script/render.js"
2:"http://localhost:40404/"
3:1024
4:768
5:0
6: "png"
```

It is called here
```
exec(
    escape([
      electron,
      `${__dirname}/script/render.js`,
      url,
      width,
      height,
      wait,
      format.toLowerCase()
    ]),
    { maxBuffer: Infinity, encoding: 'buffer' }
  ).then(({ stdout }) => stdout)
```

**Comment by juliangruber** [comment]
Can you please share the error you're getting?

**Comment by KeJunMao** [comment]
@juliangruber I have the same error
```
(node:1387) UnhandledPromiseRejectionWarning: TypeError: s.replace is not a function
    at eval (webpack:///./node_modules/shell-escape/shell-escape.js?:9:17)
    at Array.forEach (<anonymous>)
    at shellescape (webpack:///./node_modules/shell-escape/shell-escape.js?:7:5)
    at module.exports (webpack:///./node_modules/capture-electron/index.js?:15:5)
    at EventEmitter.eval (webpack:///./src/ipc/main/getPagger.ts?:9:72)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/Users/kejun/WorkSpace/storyline-push/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:335:21)
    at WebContents.emit (events.js:200:13)
(node:1387) UnhandledPromiseRejectionWarning: TypeError: s.replace is not a function
    at eval (webpack:///./node_modules/shell-escape/shell-escape.js?:9:17)
    at Array.forEach (<anonymous>)
    at shellescape (webpack:///./node_modules/shell-escape/shell-escape.js?:7:5)
    at module.exports (webpack:///./node_modules/capture-electron/index.js?:15:5)
    at EventEmitter.eval (webpack:///./src/ipc/main/getPagger.ts?:9:72)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/Users/kejun/WorkSpace/storyline-push/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:335:21)
    at WebContents.emit (events.js:200:13)
(node:1387) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1387) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1387) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1387) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by KeJunMao** [comment]
Awesome Library!!!
I'm use typescrpit, can you add `d.ts` ? THX
Looking forward to your Hui

**Comment by juliangruber** [comment]
That error seems to appear when either of `url`, `width`, 'height', `wait` or `format` is not a string or number. Can you verify that?

**Comment by KeJunMao** [comment]
Thank you for your reply!
I just use it simply:
```ts
capture({ url: "https://github.com/" }).then((s) => console.log(s));
```
After debugging, I found [that](https://github.com/juliangruber/capture-electron/blob/master/index.js#L16):
```js
escape([
  electron, // electron.replace is not a function
  `${__dirname}/script/render.js`,
  url,
  width,
  height,
  wait,
  format.toLowerCase(),
]);
```
`shell-escape.js`: 

![image](https://user-images.githubusercontent.com/18414281/79738534-75b94880-832f-11ea-9b5c-1ab05032ae9b.png)

```
TypeError: s.replace is not a function
```

**Comment by juliangruber** [comment]
Thanks! Can you try this?

```bash
node -pe 'require("electron")'
```

It seems like the electron module isn't exposing its path on your machine

**Comment by KeJunMao** [comment]
Thank you for your reply!
```bash
node -pe 'require("electron")'

/Users/kejun/WorkSpace/storyline-push/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron
```

**Comment by juliangruber** [comment]
can you please try version 3.0.2?

**Comment by niemes** [comment]
I have the same problem on Electron 9.2.0 using "capture-electron": "^3.0.2"

`Uncaught TypeError: s.replace is not a function`

Any quickFix ?

**Comment by zghbyslzf** [comment]
I have the same problem on Electron 11.5 using "capture-electron"
